# Set these values as environment variables:
#   SPRING_DATASOURCE_URL=jdbc:mysql://<url>/claymore
#   SPRING_DATASOURCE_USERNAME=<username>
#   SPRING_DATASOURCE_PASSWORD=<password>
#   SPRING_JPA_HIBERNATE_DDL_AUTO=update
#   SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQL5Dialect
#   SECURITY_OAUTH2_CLIENT_CLIENT_ID=<clientid>
#   SECURITY_OAUTH2_CLIENT_CLIENT_SECRET=<secret>

server:
  context-path: /claymore

spring:
  data:
    rest:
      basePath: /api
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

security:
    oauth2:
        client:
            accessTokenUri: https://www.googleapis.com/oauth2/v3/token
            userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
            tokenName: oauth_token
            authenticationScheme: query
            clientAuthenticationScheme: form
            scope: profile
        resource:
            userInfoUri: https://www.googleapis.com/userinfo/v2/me
            preferTokenInfo: false
