insert into claymore.non_weapon_skill (name, formula) values ('Acrobatics','(Dex*3) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Ancient Lang-Arcane*','1');
insert into claymore.non_weapon_skill (name, formula) values ('Ancient Lang-Vox','(Rc*5) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Ancient Language','(Rc*5) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Animal training','(PS*4+Rc x2) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Ambidexterity','(Dex*2) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Apothecary','(Rc*2 – 6) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Appraise','(PS*4) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Archery','(Dex*2) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Archery, water','(PS*5+Wit) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Armorer','(PS*2) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Amour repair','(PS*2+Rc*2) / 10');
insert into claymore.non_weapon_skill (name, formula) values ('Art-composition','(PS*6+Rc*2) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Art-manufacturing','(PS*5+Dex*3) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Art-performance','(PS*5+Wit*3) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Ax throwing','(Dex*2+Str – 3) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Blacksmithing','(Rc*4+Con – 1) /10');
insert into claymore.non_weapon_skill (name, formula) values ('-Weaponsmithing','(Rc*3 – 3) /10');
insert into claymore.non_weapon_skill (name, formula) values ('--Fine weaponsmithing','(Rc*3) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Bluster','(Dex*2+Wit*2) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Boating','(Dex*4+Wit*2) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Bowyer','(Dex*3+PS*2) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Brewing','(Rc*10) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Camouflage','(PS+Dex) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Carpentry','(PS*9) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Clay working','(PS*6+Dex*3) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Cobbling','(PSx 8) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Conceal combat ability','(Dex*3+Wit) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Conceal Trail','(Wit+PS – 16) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Cook','(PS*8+Rc*2) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Cooper','(Rc*6+Dex*2) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Direction Sense','(PS*6+Con) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Disguise','(Wit+PS +18) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Distilling','(Rc*8) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Drive cart','(PS*10) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Etiquette','(Rc*8+PS*2) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Engineering','(PS*4) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Farming','(Rc*8+Con*2) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Fire Starting','(Dex*6+Wit*2)/10');
insert into claymore.non_weapon_skill (name, formula) values ('Fish','(PS*6+Rc*4) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Force Marching','(Con*3) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Formation Fighting','(Con*3) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Forge','(Dex*6) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Gamble','(Wit*6+Rc*2) /10');
insert into claymore.non_weapon_skill (name, formula) values ('-Cheating','(Dex*2+Wit*2) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Glass Blowing','(Dex*5+Rc*4) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Gem Cutting','(Dex*4+PS) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Heraldry, Advanced','(Rc*10) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Herbalism','(Rc*2) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Herd','(PS*8+Wit*2) /10');
insert into claymore.non_weapon_skill (name, formula) values ('History','(Rc*10) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Hunt','(PS*6+Wit) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Jewelry Making','(Dex*4+Rc*3) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Juggling','(Dex*8) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Jumping','(Str+Dex) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Knife throwing','(Dex*3 – 3) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Knot use','(Dex*7) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Labor','(Con*4+Str) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Leather working','(Rc*6+Dex) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Lip reading','(Wit*2+ PS) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Lock-smith','(PS*2+Dex*2) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Mathematics','(PS*6) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Mine','(Rc*5) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Modern Language','(Rc*5) /10');
insert into claymore.non_weapon_skill (name, formula) values ('-Native Speech','(Wit*4+PS*2) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Mountaineering','(Dex*3+Wit) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Native Language','1');
insert into claymore.non_weapon_skill (name, formula) values ('Outdoorsman','(PS*3+Con*2) /10');
insert into claymore.non_weapon_skill (name, formula) values ('-Survival','(PS+Wit) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Poison craft','(Rc*2 – 3) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Ranger’s lore','(Rc+Wit – 9) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Read Accent','(Wit*2+Rc*2) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Read/Write','(Rc*4) /10');
insert into claymore.non_weapon_skill (name, formula) values ('-Literacy','(Rc*5) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Read/Write-Arcane*','1');
insert into claymore.non_weapon_skill (name, formula) values ('Riding','(Dex*5+Wit*3) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Run','(Con*2 - 6) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Sage','(R*5) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Sage Knowledge','(Rc*4+PS) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Seamanship','(Con*8+PS*2) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Secret Language – Cant*','(Rc*4+Wit) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Secret Language–Druid*','(Rc*4+Wit) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Secret Lang–Traveler*','(Rc*4+Wit) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Set snare','(PS*3+Dex) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Set trap','(PS*3+Rc) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Slight of hand','(Dex*2+Wit) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Spell tactics (Priest)','(PS*3) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Spell tactics (Wizard)','(PS*3) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Spell lore (Priest)','(PS*3) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Spell lore (Wizard)','(PS*3) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Strength of character','(Con+2) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Superstition','(Rc*10) /10');
insert into claymore.non_weapon_skill (name, formula) values ('-Wise man','(PS+Wit) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Swim','(Str*3+Con*3) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Tailor','(Dex*6+Rc*4) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Tactics','(PS*4) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Tend wounds','(PS*2+Wit) /10');
insert into claymore.non_weapon_skill (name, formula) values ('-Healing','(Rc*3) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Theology','(Rc*8+PS*2) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Trailing','(Wit*3 – 2) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Tightrope walking','(Dex*3) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Ventriloquism','(PS*3) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Weapon repair','(Rc*2+PS*2) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Weather Sense','(Rc*5+PS*2) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Weave','(Rc*8+ Dex*2) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Wheel Wright*','(Rc*10) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Wild animal lore','(Rc*2+Wit*2) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Wine making','(Rc*10) /10');
insert into claymore.non_weapon_skill (name, formula) values ('Wizard Lore','(PS*4) /10');